/**
 * Branches (sucursales) configuration shared across all brands
 * All brands operate from the same physical locations in Colombia
 */
export interface Branch {
  id: number;
  code: string;
  name: string;
  city: string;
  slug: string;
  schedule: string;
}

export const branchesConfig: Branch[] = [
  {
    id: 1,
    code: "AARME",
    name: "Armenia Aeropuerto",
    city: "armenia",
    slug: "armenia-aeropuerto",
    schedule: "Lun-Vie 06:00-19:00 | Sáb, Dom y fest 08:00-16:00",
  },
  {
    id: 2,
    code: "AABAN",
    name: "Barranquilla Aeropuerto",
    city: "barranquilla",
    slug: "barranquilla-aeropuerto",
    schedule: "Todos los días 07:00-20:00",
  },
  {
    id: 3,
    code: "ACBAN",
    name: "Barranquilla Norte",
    city: "barranquilla",
    slug: "barranquilla-norte",
    schedule: "Lun-Vie 08:00-16:00 | Sáb, Dom y fest 08:00-13:00",
  },
  {
    id: 4,
    code: "ACBSD",
    name: "Soledad Aeropuerto",
    city: "soledad",
    slug: "soledad-aeropuerto",
    schedule: "Lun-Dom 06:30-20:00",
  },
  {
    id: 5,
    code: "AABOT",
    name: "Bogotá Aeropuerto",
    city: "bogota",
    slug: "bogota-aeropuerto",
    schedule: "Lun-Dom 24 horas | Festivos 06:00-21:00",
  },
  {
    id: 7,
    code: "ACBEX",
    name: "Bogotá Almacén Éxito del Country",
    city: "bogota",
    slug: "bogota-almacen-exito-del-country",
    schedule: "Todos los días 06:30-20:00",
  },
  {
    id: 8,
    code: "ACBNN",
    name: "Bogotá Centro Nuestro",
    city: "bogota",
    slug: "bogota-centro-nuestro",
    schedule: "Todos los días 06:30-18:00",
  },
  {
    id: 10,
    code: "AABCR",
    name: "Bucaramanga Aeropuerto",
    city: "bucaramanga",
    slug: "bucaramanga-aeropuerto",
    schedule: "Todos los días 06:30-18:30",
  },
  {
    id: 11,
    code: "ACBCR",
    name: "Floridablanca",
    city: "floridablanca",
    slug: "floridablanca",
    schedule: "Lun-Vie 08:00-15:00 | Sáb, Dom y fest 08:00-13:00",
  },
  {
    id: 12,
    code: "AAKAL",
    name: "Cali Aeropuerto",
    city: "cali",
    slug: "cali-aeropuerto",
    schedule: "Lun-Sáb 06:00-21:00 | Dom y fest 08:00-16:00",
  },
  {
    id: 13,
    code: "ACKAL",
    name: "Cali Sur Camino Real",
    city: "cali",
    slug: "cali-sur-camino-real",
    schedule: "Lun-Sáb 08:00-16:00 | Dom y fest Cerrado",
  },
  {
    id: 14,
    code: "ACKJC",
    name: "Cali Norte Chipichape",
    city: "cali",
    slug: "cali-norte-chipichape",
    schedule: "Lun-Sáb 08:00-16:00 | Dom y fest 08:00-13:00",
  },
  {
    id: 15,
    code: "ACKPA",
    name: "Palmira",
    city: "palmira",
    slug: "palmira",
    schedule: "Lun-Vie 06:00-20:00 | Sáb, Dom y fest 08:00-15:00",
  },
  {
    id: 16,
    code: "AACTG",
    name: "Cartagena Aeropuerto",
    city: "cartagena",
    slug: "cartagena-aeropuerto",
    schedule: "Todos los días 06:30-20:00",
  },
  {
    id: 17,
    code: "AACUC",
    name: "Cúcuta Aeropuerto",
    city: "cucuta",
    slug: "cucuta-aeropuerto",
    schedule: "Lun-Vie 07:00-18:00 | Sáb, Dom y fest 08:00-15:00",
  },
  {
    id: 18,
    code: "ACIBG",
    name: "Ibagué",
    city: "ibague",
    slug: "ibague",
    schedule: "Lun-Vie 08:00-16:00 | Sáb, Dom y fest 08:00-13:00",
  },
  {
    id: 19,
    code: "ACMNZ",
    name: "Manizales",
    city: "manizales",
    slug: "manizales",
    schedule: "Lun-Vie 08:00-16:00 | Sáb, Dom y fest 08:00-13:00",
  },
  {
    id: 20,
    code: "ACMDL",
    name: "Medellín Poblado",
    city: "medellin",
    slug: "medellin-poblado",
    schedule: "Lun-Sáb 07:00-18:00 | Dom y fest 08:00-15:00",
  },
  {
    id: 21,
    code: "ACMCL",
    name: "Medellín Centro Éxito Colombia",
    city: "medellin",
    slug: "medellin-centro-exito-colombia",
    schedule: "Lun-Vie 08:00-15:00 | Sáb 08:00-13:00 | Dom y fest Cerrado",
  },
  {
    id: 22,
    code: "AAMDL",
    name: "Medellín Aeropuerto José María Córdoba",
    city: "medellin",
    slug: "medellin-aeropuerto-jose-maria-cordoba",
    schedule: "Todos los días 06:00-23:00",
  },
  {
    id: 23,
    code: "ACMJM",
    name: "Rionegro",
    city: "medellin",
    slug: "rionegro",
    schedule: "Todos los días 06:00-23:00",
  },
  {
    id: 25,
    code: "AAMTR",
    name: "Montería Aeropuerto",
    city: "monteria",
    slug: "monteria-aeropuerto",
    schedule: "Lun-Vie 07:00-19:00 | Sáb, Dom y fest 08:00-16:00",
  },
  {
    id: 26,
    code: "ACMTR",
    name: "Montería Ciudad",
    city: "monteria",
    slug: "monteria-ciudad",
    schedule: "Lun-Vie 08:00-15:00 | Sáb, Dom y fest 08:00-13:00",
  },
  {
    id: 27,
    code: "AANVA",
    name: "Neiva Aeropuerto",
    city: "neiva",
    slug: "neiva-aeropuerto",
    schedule: "Lun-Vie 06:30-20:00 | Sáb, Dom y fest 08:00-15:00",
  },
  {
    id: 28,
    code: "AAPEI",
    name: "Pereira Aeropuerto",
    city: "pereira",
    slug: "pereira-aeropuerto",
    schedule: "Lun-Vie 06:30-19:30 | Sáb, Dom y fest 08:00-15:00",
  },
  {
    id: 30,
    code: "AASMR",
    name: "Santa Marta Aeropuerto",
    city: "santa-marta",
    slug: "santa-marta-aeropuerto",
    schedule: "Todos los días 07:00-18:00",
  },
  {
    id: 31,
    code: "AAVAL",
    name: "Valledupar Aeropuerto",
    city: "valledupar",
    slug: "valledupar-aeropuerto",
    schedule: "Lun-Vie 07:00-18:00 | Sáb, Dom y fest 08:00-15:00",
  },
  {
    id: 32,
    code: "ACVLL",
    name: "Villavicencio",
    city: "villavicencio",
    slug: "villavicencio",
    schedule: "Lun-Vie 08:00-16:00 | Sáb, Dom y fest 08:00-13:00",
  },
];
